<?php
$ville="";
include_once "../includes/header.php";
include_once "../includes/left.php";
?>
<div class="milieu" style="margin-top: 130px;">
    <div id="navbas" style="    text-align: center;"> <!-- navigation dans la destination --><strong style="background-color:#FFCC00">Le Grand Sud</strong> | <a href="sud-tichka.htm">Col du Tichka </a> | <a href="sud-haddou.htm">Ait ben Haddou</a> | <a href="sud-ouarzazate.htm">Ouarzazate</a> | <a href="sud-dades.htm">Vallée du Dades</a> | <a href="sud-tineghir.htm">Tineghir</a> | <a href="sud-todra.htm">Gorges du Todra</a> | <a href="sud-merzouga.htm">Dunes de Merzouga</a> | <a href="sud-rissani.htm">Rissani </a>| <a href="sud-erfoud.htm">Erfoud</a> | <a href="sud-tafilalet.htm">Palmeraie de Tafilalet</a> | <a href="sud-ziz.htm">vallée du Ziz</a> | <a href="sud-rachidia.htm">Rachidia</a> | <a href="sud-midelt.htm">Midelt</a> | <a href="sud-azrou.htm">Azrou</a> | <a href="sud-ifrane.htm">Ifrane</a> | 
			    <br>
			    <strong style="background-color:#FFCC00">Les villes Impériales</strong> | <strong style="background-color:#FFCC00"><a href="fes.htm">Fès</a></strong> | <strong style="background-color:#FFCC00"><a href="fes-bali.htm">Fès el bali </a></strong>| <a href="fes-moulay.htm">Zaouïa de Moulay Idriss</a> |<a href="fes-nejarine.htm">fondouk  en Nejarine</a> |  <a href="fes-karaouiyne.htm">Mosquée Karaouiyine</a> | <a href="fes-tanneurs.htm">Quartier des tanneurs</a> | <a href="fes-djelloud.htm">Bab Bou Djelloud ou Boujloud :  la porte bleue</a> | <a href="fes-tariana.htm">palais Tariana</a> | <a href="fes-medersa.htm">Medersa Bou Inania</a> | <strong style="background-color:#FFCC00"><a href="fesd-jedid.htm">Fès El Djedid</a></strong> |  <a href="fes-makjzen.htm">Dar el Makhzen</a> | <a href="fes-mellah.htm">Mellah</a> |			    <a href="moulay.htm">Moulay Driss</a> | <strong style="background-color:#FFCC00"><a href="volubilis.htm">Volubilis</a></strong> |			    <strong style="background-color:#FFCC00"><a href="meknes.htm">Meknès</a></strong> | <a href="meknes-hedime.htm">Place El-Hédime</a> | <a href="meknes-mansour.htm">Bab Mansour</a>; | <a href="meknes-agdal.htm">Bassin de l' Agdal</a> |  <a href="meknes-greniers.htm">Les greniers de Moulay</a> | <a href="meknes-rih.htm">bab er Rih</a> | <a href="meknes-mausolee.htm">Mausolée de Moulay Ismael</a> | <strong style="background-color:#FFCC00"><a href="rabat.htm">Rabat</a></strong> |  <a href="rabat-medina.htm">Médina</a> |  <a href="rabat-kasbah.htm">Kasbah des Oudaïa</a> | <a href="rabat-andalous.htm">les murailles de Rabat</a> |  <a href="rabat-palais.htm">Palais Royal </a> | <a href="rabat-chellah.htm">Nécropole de Chellah</a> | <a href="rabat-mohamedV.htm">Mausolée Mohamed V</a> | <a href="rabat-tour.htm">la tour Hassan</a> |  <br>
			   | 
			   <strong style="background-color:#FFCC00">Casablanca</strong> : <a href="casa-mosquee.htm">la mosquée Hassan II </a> |			   <a href="jadida.htm">El Jadida </a>| <a href="oualidia.htm">Oualidia </a>|			   <strong style="background-color:#FFCC00"><a href="safi.htm">Safi</a> </strong>| <a href="safi-fortifications.htm">fortifications</a> | <a href="safi-portugais.htm">Cathédrale portugaise</a>  | <a href="safi-potiers.htm">souk des potiers</a> | <a href="safi-phosphore.htm"> usine de phosphore</a> |<strong style="background-color:#FFCC00"><a href="essaouira.htm">Essaouira</a></strong> |  <a href="essaouira-place.htm">place Moulay el Hassan</a> |<a href="essaouira-medina.htm"> médina et souks</a> | <a href="essaouira-mellah.htm">Mellah</a> | <a href="essaouira-bastionnord.htm">bastion nord</a> | <a href="essaouira-kasbah.htm">sqala de la kasba</a> | <a href="essaouira-port.htm">le port</a> |  <a href="essaouira-squala-port.htm">sqala du port</a> |   <a href="essaouira-mer.htm">le bord de mer</a> |			  <a href="argan.htm">Coopérative féminine Marjana&nbsp; pour l'extraction de l'huile d'argan</a> | <strong style="background-color:#FFCC00"><a href="../marrakech/index.htm">Marrakech</a></strong> | <br>
			   
<br></div>
</div>
<?php
include_once "../includes/right.php";
include_once "../includes/footer.php";